on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: on tente des trucs
    outputs:
      output1: ${{ steps.Test.output.test}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build
        id: Build
        uses: LuckMk1-evil-organization/simple-python-pyinstaller-app/actions/build@master
      - name: Test
        id: Test
        uses: LuckMk1-evil-organization/simple-python-pyinstaller-app/actions/test@master
      - name: Save code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ${{ github.workspace }}/sources/results.xml
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ${{ github.workspace }}/pytest-coverage.txt
          junitxml-path: ${{ github.workspace }}/sources/results.xml
      - name: Deliver
        id: deliver
        uses: LuckMk1-evil-organization/simple-python-pyinstaller-app/actions/deliver@master
