on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: on tente des trucs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build
        id: Build
        uses: LuckMk1-evil-organization/simple-python-pyinstaller-app/actions/build@master
      - name: Test
        id: Test
        uses: LuckMk1-evil-organization/simple-python-pyinstaller-app/actions/test@master
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: /results.xml
          junitxml-path: /pytest.xml
